### ISSUE TITLE
Can't run scan using headless-burp extension

### ISSUE THREAD

**Issue by IgorSasovets** [NetsOSS/headless-burp#14]
Hi, team! I installed Headless Burp extension in BurpSuite Professional and want to automate my web application security assessment process. I managed to start Burp using the extension, run API tests through BurpProxy and save all collected data to the burp project. Problem is that I cannot stop proxy and start scanning from terminal. Could you please help me with this issue?

Command that I use to start Burp:
```
java -Xmx1G -Djava.awt.headless=true -classpath headless-burp-proxy-master-SNAPSHOT-jar-with-dependencies.jar:burpsuite_pro.jar burp.StartBurp --project-file=web-scan.burp -c config.xml -v
```

Config file:
```
<?xml version="1.0" encoding="UTF-8"?>
<config>
  <reportType>JUNIT</reportType>
  <targetSitemap><![CDATA[http://localhost:5000/]]></targetSitemap>
</config>
```

To stop proxy I used below command:
```
echo SHUTDOWN >> /dev/tcp/127.0.0.1/8080
```

BurpSuite version: 2.0.13 beta
Extension version: 1.0

**Comment by anandsudhir** [comment]
Hi @IgorSasovets ,

Are you sure the proxy is listening on `8080`? The Proxy listens to `4444` by default, unless overridden.

Could you try one of these documented commands?
```sh
echo SHUTDOWN >> /dev/tcp/127.0.0.1/4444
or
echo SHUTDOWN | netcat 127.0.0.1 4444
or
echo SHUTDOWN | ncat 127.0.0.1 4444
```

**Comment by IgorSasovets** [comment]
Hi, @anandsudhir ! Thanks for quick response. I tried to override port using `-shutdownPort` argument but there still are some issues. Here is output of quoted commands:
1.
```
user@ubuntu:~$ echo SHUTDOWN >> /dev/tcp/127.0.0.1/4444
user@ubuntu:~$ 
```
2.
```
user@ubuntu:~$ echo SHUTDOWN | netcat 127.0.0.1 4444
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad Requestuser@ubuntu:~$ 
```
3.
```
user@ubuntu:~$ echo SHUTDOWN | netcat 127.0.0.1 4444
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad Requestuser@ubuntu:~$ 
```

**Comment by anandsudhir** [comment]
Could you paste the output you get when you run the burp suite with proxy?
`java -Xmx1G -Djava.awt.headless=true -classpath headless-burp-proxy-master-SNAPSHOT-jar-with-dependencies.jar:burpsuite_pro.jar burp.StartBurp --project-file=web-scan.burp -v`

Also, could you check what ports burp + the externsion are listening to?
atleast `netstat -tulpn | grep 4444`

**Comment by anandsudhir** [comment]
Use something like `--shutdown-port 5555` override the port

**Comment by IgorSasovets** [comment]
Command output:
![screen shot 2019-02-12 at 4 51 07 pm](https://user-images.githubusercontent.com/27974884/52643842-7910a300-2ee6-11e9-89ab-6f18b06a9ba9.png)

`netstat -tulpn | grep 4444`
![screen shot 2019-02-12 at 4 53 33 pm](https://user-images.githubusercontent.com/27974884/52644020-cd1b8780-2ee6-11e9-8a5e-91e8ab311870.png)

You were right, port is already in use. I restarted proxy with custom port (after I reassured that it is unused by another service):
```
java -Xmx1G -Djava.awt.headless=true -classpath headless-burp-proxy-master-SNAPSHOT-jar-with-dependencies.jar:burpsuite_pro.jar burp.StartBurp --project-file=web-scan.burp -v -shutdownPort 8081
```
Then again tried to send `SHUTDOWN` command to port `8081`:
1. 
```
user@ubuntu:~$ echo SHUTDOWN >> /dev/tcp/127.0.0.1/8081
bash: connect: Connection refused
bash: /dev/tcp/127.0.0.1/8081: Connection refused
user@ubuntu:~$
```
2.
```
user@ubuntu:~$ echo SHUTDOWN | netcat 127.0.0.1 8081
user@ubuntu:~$
```
3.
```
user@ubuntu:~$ echo SHUTDOWN | nc 127.0.0.1 8081
user@ubuntu:~$
```

**Comment by anandsudhir** [comment]
Did that work? If it did, the proxy process must have exited.
I cant see if it worked or not from these logs :(

**Comment by IgorSasovets** [comment]
When used `--shutdown-port` received `Unrecognized command-line argument: --shutdown-port`.
Nope, proxy still running:
![screen shot 2019-02-12 at 5 04 10 pm](https://user-images.githubusercontent.com/27974884/52644842-4667aa00-2ee8-11e9-9cc6-664339f2ddb2.png)

**Comment by anandsudhir** [comment]
Ok, I see the issue now.
The proxy plugin isnt loaded on your classpath and hence the proxy shutdown listener is loaded either. Make sure you have `headless-burp-proxy-master-SNAPSHOT-jar-with-dependencies.jar` on the classpath

**Comment by anandsudhir** [comment]
If the extension is on the classpath and loaded, you will see something like this below (note logs from the extension)

```
java -Xmx1G -Djava.awt.headless=true -classpath headless-burp-proxy-master-SNAPSHOT-jar-with-dependencies.jar:burpsuite_pro.jar burp.StartBurp --project-file=web-scan.burp -v

Suite: Environment not supported by embedded browser
Proxy: Proxy service started on 127.0.0.1:8080
Extender: Legacy extension found
Extender: Headless Burp Proxy: Arguments to headless burp: -v
Proxy: Proxy service stopped on 127.0.0.1:8080
Proxy: Proxy service started on 127.0.0.1:4646
Extender: Headless Burp Proxy: Using proxy 127.0.0.1:4646
Extender: Headless Burp Proxy: Headless Burp Proxy fully configured
```

**Comment by IgorSasovets** [comment]
@anandsudhir , one more question: how I can check this, in `burpsuite_pro.jar` (sorry for such question, but I'm not a Java developer)?

**Comment by anandsudhir** [comment]
Do you have the file headless-burp-proxy-master-SNAPSHOT-jar in the same directory as the burp suite jar? If not, you can follow the documentation on his to build the project and thst so generate the hat for you.

Basically you need to run `./mvnw clean install`

**Comment by IgorSasovets** [comment]
Thanks so much. I'll try to build the project and notify you about the results.

**Comment by IgorSasovets** [comment]
@anandsudhir , now file located in the same folder as the burp jar, but SHUTDOWN still not works.
![screen shot 2019-02-12 at 6 01 09 pm](https://user-images.githubusercontent.com/27974884/52649336-ceea4880-2ef0-11e9-95d5-fb3af1797789.png)

**Comment by anandsudhir** [comment]
You want the proxy jar in the same directory. I see that you have the scanner. Copy the proxy jar too and finally 8 hope it works for you

**Comment by IgorSasovets** [comment]
I didn't find "proxy.jar". Do I need to install additional plugin through BurpSuite extender or I was looking for wrong file?

**Comment by anandsudhir** [comment]
The file is named headless-burp-proxy-master-SNAPSHOT-jar and would be under the headless-burp-proxy/target directory after you run mvnw clean install

**Comment by IgorSasovets** [comment]
I made clean install, reassured that required files are located in the same directory, but after I started burp using plugin it finished unexpectedly. After that I tried to download extension as ".jar" file and BurpSuite crashed completely. Now I cannot even open it. Which version of BurpSuite do you use?
![screen shot 2019-02-12 at 6 40 37 pm](https://user-images.githubusercontent.com/27974884/52652073-16270800-2ef6-11e9-9565-53389b5ba900.png)

**Comment by IgorSasovets** [comment]
Also, all installed extensions were unloaded after crash.

**Comment by anandsudhir** [comment]
Hm, that's very strange. I run this with both 1.x and 2.x versions and it loads just fine.

Here's my suggestion now.
Run this without any plugins on the classpath and see what happens.

**Comment by anandsudhir** [comment]
Btw,  i miswrote the jar filename. You need the one that says wit

**Comment by IgorSasovets** [comment]
@anandsudhir , I'll try it and provide you the results.

**Comment by IgorSasovets** [comment]
@anandsudhir , here is files list of the BurpPro folder with burp jar:
![screen shot 2019-02-13 at 10 56 26 am](https://user-images.githubusercontent.com/27974884/52699462-76618c80-2f7e-11e9-8756-3a01b687235b.png)

When I run command to start burp I receive below: 
![screen shot 2019-02-13 at 10 58 41 am](https://user-images.githubusercontent.com/27974884/52699500-8d07e380-2f7e-11e9-9fbe-6a6c8a5edbd2.png)

I unloaded Burp headless extension, but unfortunately it didn't fix the problem. Could you please provide `ls` command results from your Burp folder? Maybe I copied wrong files.

**Comment by IgorSasovets** [comment]
After `Legacy extension found` message it finished unexpectedly

**Comment by anandsudhir** [comment]
Hmm, crashed after that line? Ok,

What if you just run 
java -Xmx1G -jar burpsuite_pro.jar`? If that doesnt work either, add `--use-defaults`

**Comment by anandsudhir** [comment]
I have these files in my directory

```
$ ls *burp*
burpsuite_pro_v1.7.37.jar  burpsuite_pro_v2.0.08beta.jar headless-burp-proxy-master-SNAPSHOT-jar-with-dependencies.jar  headless-burp-scanner-master-SNAPSHOT-jar-with-dependencies.jar
```

**Comment by IgorSasovets** [comment]
It just started Burp in UI mode after `java -Xmx1G -jar burpsuite_pro.jar` command

**Comment by anandsudhir** [comment]
Yes, check if there are some weird  extension settings. Also unload old headless burp extensions. Try again with the extension jars. Btw, you could also download these from github releases too

**Comment by IgorSasovets** [comment]
Now I have problems with shutdown port, provided option not recognized:
![screen shot 2019-02-13 at 11 40 21 am](https://user-images.githubusercontent.com/27974884/52702044-2dacd200-2f84-11e9-974c-9783048bcda5.png)
![screen shot 2019-02-13 at 11 40 06 am](https://user-images.githubusercontent.com/27974884/52702046-2dacd200-2f84-11e9-9def-38f18eb46099.png)

**Comment by IgorSasovets** [comment]
Finally! I fixed issue with shutdown proxy:
```
java -Xmx1G -Djava.awt.headless=true -classpath headless-burp-proxy-master-SNAPSHOT-jar-with-dependencies.jar:burpsuite_pro.jar burp.StartBurp --project-file=web-scan.burp -v --shutdown-port 8081
```

But I still have issue with config file. Also, have I can start scan now?

**Comment by IgorSasovets** [comment]
I start scanner using below command:
```
java -Xmx1G -Djava.awt.headless=true -classpath headless-burp-scanner-master-SNAPSHOT-jar-with-dependencies.jar:burpsuite_pro.jar burp.StartBurp --project-file=web-scan.burp -c config.xml
```
but each time receive an error:
![screen shot 2019-02-13 at 12 00 50 pm](https://user-images.githubusercontent.com/27974884/52703551-41a60300-2f87-11e9-81c1-4fe3c9f2e2f1.png)

**Comment by anandsudhir** [comment]
You are using the wrong switch, Use `-c` to pass config.xml. See documentation

**Comment by IgorSasovets** [comment]
I tried, but it doesn't work:
![screen shot 2019-02-13 at 12 53 21 pm](https://user-images.githubusercontent.com/27974884/52706580-6f427a80-2f8e-11e9-80eb-59088a9e7082.png)

**Comment by IgorSasovets** [comment]
Finally fixed all issue! Now it works as expected. @anandsudhir , I would add complete example (something similar to step by step guide) for extension usage. I can open PR for it. Because in my case it would be very useful and would save a lot of time.

**Comment by IgorSasovets** [comment]
@anandsudhir , thanks so much for your time, really appreciate it. I will prepare full example of usage and submit a PR. I think that we can close this issue.

**Comment by anandsudhir** [comment]
Happy to help :) Looking forward to the PR.
