### ISSUE TITLE
How to generate report using headless-burp extension?

### ISSUE THREAD

**Issue by IgorSasovets** [NetsOSS/headless-burp#15]
Hi, team! Thanks for all the work made on this extension. It's really helpful. I have a question regarding report generation. Are there any ways to generate a BurpSuite report using `headless-burp` extension? Thanks in advance.

**Comment by anandsudhir** [comment]
When you use the headless-burp-scanner extension, you can generate burp report in 3 formats, JUNIT, HTML and XML
. e.g. `<reportType>HTML</reportType>`. 

See https://github.com/NetsOSS/headless-burp/blob/master/README.md#configuration

**Comment by IgorSasovets** [comment]
Thanks, @anandsudhir . Closing the issue.
