### ISSUE TITLE
config-file error on XML

### ISSUE THREAD

**Issue by michaelsmitasin** [NetsOSS/headless-burp#20]
The documentation refers to using XML for the config-file, but when attempting to do so, for example:

`java -Xmx1G -Djava.awt.headless=true -classpath burpsuite_pro.jar burp.StartBurp --project-file=example.burp --config-file=example.xml`

Where example.xml is:

`<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://nets.eu/burp/config">
    <reportType>HTML</reportType>
    <targetSitemap><![CDATA[http://example.com]]></targetSitemap>
</config>
`

It returns the error as if it expects JSON:

`Invalid JSON configuration found at:  >>>  <<< ?xml versi - Unexpected '<' at [line 1, column 1]`

**Comment by michaelsmitasin** [comment]
Sorry, example.xml was stripped, see below:

`<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://nets.eu/burp/config">
    <reportType>HTML</reportType>
    <targetSitemap><![CDATA[http://example.com]]></targetSitemap>
</config>
`

**Comment by anandsudhir** [comment]
You're usingthe wrong command line argument. Note that the documentation says use`-c (--config) <file> ` to pass the XML config file. 

`--config-file` is for passing Burp's own project config file.
