### ISSUE TITLE
Generate XML report with request and reposne in plain text.

### ISSUE THREAD

**Issue by karunguduru** [NetsOSS/headless-burp#21]
Hi,

Looking for info as how to generate the XML report where the request and response are not base64 encoded.
I have raised the issue with burp support team, link for reference
https://support.portswigger.net/customer/portal/private/cases/318118

Please could you provide help/info on this one.

Looking for quick help how can we get an XML report with base64 as false <request method="GET" base64="false">. I mean I need request and response in plain text rather than base64 encoded. 
I ran burp in headless mode. 
java -jar -Xmx1g -Djava.awt.headless=true "C:\Program Files\BurpSuitePro\burpsuite_pro.jar" --config-file=burpprojectoptions1.json --project-file=project.burp -c config.xml 

confix.xml will have the below data: 
<?xml version="1.0" encoding="UTF-8"?> 
<config xmlns="http://nets.eu/burp/config"> 
 <reportType>XML</reportType> 
	<targetSitemap><![CDATA[http://[Host]/dvwa]]></targetSitemap> 
 <scope> 
 <url><![CDATA[http://[Host]/dvwa/]]></url> 
 <exclusions>  
 <exclusion><![CDATA[http://[Host]/dashboard/]]></exclusion> 
 <exclusion><![CDATA[http://[Host]/phpmyadmin/]]></exclusion> 
 </exclusions> 
 </scope> 
</config>

**Comment by anandsudhir** [comment]
@karunguduru 

I am not sure you can do that using just the burp extender api. It doesn't seem to have any options for that.
However, I wanted the same as you at some point and hence wrote an `xsl` to transform the burl XML report to a JUnit style format. Int his process, the request/response are also base64 decoded.

See [headless-burp-scanner/src/main/resources/burp-to-junit.xsl](https://github.com/NetsOSS/headless-burp/blob/master/headless-burp-scanner/src/main/resources/burp-to-junit.xsl). Especially the below snippet. Perhaps you could do something similar? Else, you could use the `<reportType>JUNIT</reportType>` option in you `config.xml` too

```xsl
<system-out>
  <xsl:text disable-output-escaping="yes">&lt;![CDATA[</xsl:text>
  <xsl:text>Request:</xsl:text>
  <xsl:value-of select="$newline" disable-output-escaping="no"/>
  <xsl:value-of disable-output-escaping="yes" select="base64:decodeBase64(requestresponse/request)"/>
  <xsl:text disable-output-escaping="yes">]]&gt;</xsl:text>
</system-out>
```
