### ISSUE TITLE
How to define session cookie 

### ISSUE THREAD

**Issue by yehgdotnet** [NetsOSS/headless-burp#23]
Hello 

I read about documentation but couldn't find how to set a session cookie in config.xml 

Thank you

**Comment by anandsudhir** [comment]
Hi  @yehgdotnet 

Sorry for the late reply.
`config.xml` here only configures the headless scanner extension. Defining session cookies or any session handling for that matter is out of scope of the plugin.
You might want to use Burp's in-built session handling features for that. Perhaps use a authenticatioin macro?
