### ISSUE TITLE
Headless Burp. Auto SCAN. Initiated the Burp in Project loaded mode.

### ISSUE THREAD

**Issue by stringz** [NetsOSS/headless-burp#5]
Hi, 
After going through all your documents, especially, the one on https://netsoss.github.io/headless-burp/user-guide/burp-extensions/headless-burp-scanner/, I am trying to automate BURP with my existing Security Testing. I have been able to run my Pro Version of Burp through your extension.
But I can't get it to SCAN it. 
I am running this command on Windows Server 2012.

$ java -Xmx2G -classpath headless-burp-scanner-master-SNAPSHOT-jar-with-dependencies.jar;"C:\Program Files\BurpSuitePro_v1.7.37\burpsuite_pro.jar" burp.StartBurp --project-file="E:\Burp_sessions\IRIS5.burp" -c config.xml --use-defaults
[command.txt](https://github.com/NetsOSS/headless-burp/files/2336192/command.txt)

BURP just opens with **my project file** already loaded. **The scan isn't initiated**. Can you help me, what I am doing wrong.

**Comment by anandsudhir** [comment]
Try adding another param `--unpause-spider-and-scanner`. This will ensure that hte spider/scanner is not paused upon launch (I believe that is the default setting).

Also, you can also try to install the extension from [BApp store](https://portswigger.net/bappstore/d54b11f7af3c4dfeb6b81fb5db72e381) instead.

Let me know if it this fixes your issue

**Comment by stringz** [comment]
Thanks Anand. Didn't know you reply so early. Will try and let you know. I have added the extension from BApp Store.

**Comment by anandsudhir** [comment]
I have now updated the documentation to include `--unpause-spider-and-scanner` in [this commit](https://github.com/NetsOSS/headless-burp/commit/b7a6c4b314bf5c5ba642df197c8596b26946fad6)

**Comment by anandsudhir** [comment]
@stringz Can I close the issue now?

**Comment by anandsudhir** [comment]
What do you have in the config.xml? Did you follow the instructions as on the the documentation?

Make sure you specify the site map url correctly in the config.xml

The extension seem to work very well for a lot of ppl out there so I suspect something is off with your config.

Also, you should get some "logs" in the alerts tab on burp or on the console if you run it headless. Could you paste the logs here?

**Comment by stringz** [comment]
Hi Anand. 

The Burp ran automatically via command line, not headless, GUI was displayed, but the Scanner is sending URLs to spider and it is stuck over sending the urls, **not scanning at all**. 

Please find my config.xml changed to config.txt, ALERTS Tab Export and Logs.

[config.txt](https://github.com/NetsOSS/headless-burp/files/2352980/config.txt)
[Alerts.txt](https://github.com/NetsOSS/headless-burp/files/2352975/Alerts.txt)
[Logs.txt](https://github.com/NetsOSS/headless-burp/files/2352976/Logs.txt)

**Comment by anandsudhir** [comment]
Your logs show that the extension is sending the urls to the scanner. So, basically. Doing what it is supposed to do. 
But seems that the scanner maybe paused. Could you try and manually start it this once n see if that works? It could be some weird local setup overriding the u pause scanner option?

**Comment by anandsudhir** [comment]
also, what is the `--use-defaults` for? Perhaps you should get rid of it and try

**Comment by stringz** [comment]
Hi 
this is the new command. 
java -Xmx2G -classpath headless-burp-scanner-master-SNAPSHOT-jar-with-dependencies.jar;"C:\Program Files\BurpSuitePro_v1.7.37\burpsuite_pro.jar" burp.StartBurp --project-file="E:\Burp_sessions\IRIS.burp" -c "E:/Burp_sessions/config.xml"


Still, the BURP is waiting for the spider to finish. Then the Scan will run. 

any way, that scan could be ran ? 
[Logs_1.txt](https://github.com/NetsOSS/headless-burp/files/2361035/Logs_1.txt)
[Alerts_1.txt](https://github.com/NetsOSS/headless-burp/files/2361036/Alerts_1.txt)
[config.txt](https://github.com/NetsOSS/headless-burp/files/2361037/config.txt)

**Comment by anandsudhir** [comment]
I am not sure I understand, the whole spider and scan process does take a lot of time. Especially when you have a lot of urls and requests to be scanned. In some of the projects I have used burp on, the scan takes quite a few hours and thsts why I run it as a nightly build.

So, I am sorry, you just have to wait until the scan is finished.

**Comment by anandsudhir** [comment]
@stringz please reopen the issue if the previous didn't help
