### ISSUE TITLE
How to install in a CentOS machine without GUI.

### ISSUE THREAD

**Issue by Greatonaz** [NetsOSS/headless-burp#9]
I've been trying to install everything from scratch into a CentOS machine running Jenkins. I'm not clear on how to install it in that machine without the GUI and how to install the plugin into the project using Gradle instead of Maven. Thank you so much for an awesome project.

**Comment by anandsudhir** [comment]
Hi,

Thank you, I'm glad you like the project :) 

Please take a look at https://netsoss.github.io/headless-burp/getting-started/. It contains instructions on installing burp suite pro headless and other things to get you stated. The grade point is interesting. But. You don't need maven installed on your machine, the project uses maven wrapper so, you can just run `. /mvnw` and that should build all the modules for you. 
You can Ofcourse download the release artifacts from github itself 

Let me know this works for you.

**Comment by anandsudhir** [comment]
@Greatonaz Please reopen the issue if my previous Comment didn't help
